---
title: "Project Process"

---

# Data Description

**Identify your data source.**  
My data comes from the NOAA Fisheries Commercial Landings Database, which tracks reported commercial landings of fishes. I utilized their website to select data for 12 large pelagic shark species landed across the U.S.

https://www.fisheries.noaa.gov/foss/f?p=215:200:1455472432287:::::


**Describe your data, including variables and data types.**  
My data contains commercial fisheries landings from 1915 to 2023, and provides insight into trends in shark landings  by state.
The dataset includes the following variables:
 - Year, year of the recorded landings.
 -State, U.S. state 
 - NMFS Name, National Marine Fisheries Service common name of each species
 - Pounds and Metric Tons, weight of sharks landed
 - Dollars, market value of the landed sharks
 - Confidentiality, whether or not the data is  confidential
 - Collection, whether it was commercially or recreational caught
 - Scientific Name, scientific name of each species
 - Tsn,  Taxonomic Serial Numbers are a numeric code for the species
 - Source,original source of the data

**Identify the research questions you want to answer.**  

1. Which shark species have the highest commercial landing weights (weight of all sharks cought) over time?

2. How do the prominent species landed vary by state?

3. Are there trends in the value of shark landings (in dollars) over time, for the shark species that can legally be kept and sold??

4. What data source (fisheries management organization) had the highest average shark landings in the last 5 years?

# Data Visualization

**What do you want your final visualizations to look like?**  
I want my final visualizations to clearly display trends in shark landings over time, differences among the US states, and the range of relationships between landing weight and commercial value for each species. I plan to create a line graph showing changes in landings (in pounds or metric tons) for all shark species over time. I will also create a bar chart that compares the total market value of shark landings by state. I will use a scatterplot to examine the relationship between the weight of landings and their dollar value. 

**What do you want to highlight on your final visualizations in order to answer your research questions? How do you plan to do that?**  
I want to highlight the top shark species caught by weight and commercial value. I will use color coding to distinguish species and states and apply faceting to break up graphs by category where needed, inorder to include more varibles on each graph. 


**What is missing from your data or would need to change in your data to create these visualizations?**  
Some aspects of the data may need to be adjusted before I can create these visualizations. I will need to group the data by species, year, and state in order to calculate some summary statistics. I will also need to check whether the State and NMFS Name variables are properly formatted for use as categorical variables. 

# Data Cleaning

> _The answer to at least three of these questions should be “YES” for the data to meet the necessary standards to demonstrate your cleaning._

**Do you need to reformat any variables into different types (e.g., factors, time, dates, strings)? Or remove information from variable values?**  
Yes: I’ll convert Year to a date type, and State, NMFS Name, and Scientific Name into factors for plotting.

**Do you need to deal with any missing data, especially missing data coded other than NA?**  
Yes: There will be many blank cells in the value column, because some of these species are illegal to keep, and therefore have no true market value. 

**Do you need to filter your data? How?**  
Yes: I will filter out uneccessary cells such as collection and tsn.

**Do you need to create any new variables? What variables? How?**  

Yes: I may create a variable for “Region” by grouping  States together.


**Do you need to add new data (join) to your data? What data? How?**  

No: I should not have to perform any joins unless I decide to add the regions by joining another dataset. 


**Are there any variables you can exclude from your data?**  

Yes: Variables like Tsn, and Collection are not relevant to my project.

**Do you need to pivot your data in any way? Why? How?**  
Yes: I may pivot my data to combine species across years or states. 


**Do you need to summarize any of the variables? Which ones? How?**  

Yes: I plan to summarize total landings and total dollar value by species, state, and year using group_by and summarize.

**What other aspects of your data need to be “fixed” in order to make your data visualizations?**  
I may need to standardize state names and abbreviations, and handle zero values in landings and value.