---
title: "About"
---

Alyssa Walter graduated with her B.S. in Marine Science and a Statistics minor from California State University, Monterey Bay in May 2025. She began conducting research as a freshman with Dr. Alison Haupt, and later joined the Ocean Predator Ecology Lab under Dr. Salvador Jorgensen, where she led a project analyzing injuries on great white sharks. Project Shark Scar is an undergraduate-driven initiative to study insights into shark life histories, reproduction, behavior, and anthropogenic threats. Alyssa also developed a shark education outreach program through the lab to foster conservation awareness among students and residents in Monterey County. As a NOAA Hollings Scholar, she interned with the Channel Islands National Marine Sanctuary where she analyzed elasmobranch movement with satellite telemetry and contributed to science communication efforts. Alyssa was fortunate to receive support through programs such as LSAMP, UROC Scholars, NOAA Hollings, CSU COAST, PALiISaDS, and the Sally Casanova California Pre-Doctoral Scholarship during her time as an undergraduate at CSUMB.
Beyond research, Alyssa served as the Associated Students College of Science Senator, Chair of the AS Committee of Colleges, and sat on multiple committees shaping the future of CSU Monterey Bay’s infrastructure and leadership. She was also a four-year member of the Otter Dance Team, and loved to represent CSUMB at national collegiate dance competitions. 
Alyssa intends to pursue a Ph.D. where she can continue studying the movement ecology and reproductive behaviors of marine top predators to support conservation efforts for species of ecological and economic importance. 